/**
 * Agent-side session file reader.
 * Reads Claude CLI JSONL session files from ~/.claude/projects/<path-hash>/
 */
import { readdir, readFile, stat } from 'fs/promises';
import { createReadStream, existsSync, readdirSync } from 'fs';
import { createInterface } from 'readline';
import { join } from 'path';
import { homedir } from 'os';

export interface SessionListItem {
  sessionId: string;
  firstPrompt: string;
  lastModified: string;
  fileSize: number;
  gitBranch?: string;
  isActive?: boolean;
}

const ACTIVE_THRESHOLD_MS = 120_000; // 120 seconds

export interface SessionTimelineEntry {
  id: string;
  type: 'output' | 'tool_use' | 'tool_result' | 'user_message';
  timestamp: number;
  content: string;
  toolName?: string;
  toolInput?: unknown;
  toolResult?: unknown;
}

const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/**
 * Check if a message is a CLI command/skill invocation (e.g. /login, /commit).
 */
function isCommandMessage(content: string): boolean {
  return /<command-name>/.test(content.trim());
}

/**
 * Check if a message is a continuation summary (auto-generated by CLI on context overflow).
 */
function isContinuationMessage(content: string): boolean {
  return content.trimStart().startsWith('This session is being continued from a previous conversation');
}

/**
 * Clean up Claude CLI internal tags from user messages.
 * Returns null if the message is purely a system/internal message that should be hidden.
 */
function cleanUserMessage(content: string): string | null {
  const trimmed = content.trim();

  if (/^<local-command-caveat>[\s\S]*<\/local-command-caveat>$/.test(trimmed)) return null;
  if (/^<local-command-stdout>[\s\S]*<\/local-command-stdout>$/.test(trimmed)) return null;

  // Command invocations: prefer <command-message> (clean name) over <command-name> (may have /)
  const cmdNameMatch = trimmed.match(/<command-name>([^<]+)<\/command-name>/);
  if (cmdNameMatch) {
    const cmdMsgMatch = trimmed.match(/<command-message>([^<]+)<\/command-message>/);
    const rawCmd = cmdMsgMatch ? cmdMsgMatch[1].trim() : cmdNameMatch[1].trim();
    const cmd = rawCmd.replace(/^\/+/, ''); // strip leading slash
    const argsMatch = trimmed.match(/<command-args>([\s\S]*?)<\/command-args>/);
    const args = argsMatch?.[1]?.trim();
    return args ? `/${cmd} ${args}` : `/${cmd}`;
  }

  const taskNotifMatch = trimmed.match(/<task-notification>[\s\S]*?<summary>([^<]+)<\/summary>[\s\S]*?<\/task-notification>/);
  if (taskNotifMatch) {
    return `[Task] ${taskNotifMatch[1].trim()}`;
  }

  // Continuation summaries: show compact marker
  if (isContinuationMessage(trimmed)) {
    return '[Continued from previous session]';
  }

  // Strip known internal blocks entirely (content + tags)
  let cleaned = content;
  cleaned = cleaned.replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '');
  cleaned = cleaned.replace(/<local-command-caveat>[\s\S]*?<\/local-command-caveat>/g, '');
  cleaned = cleaned.replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g, '');
  cleaned = cleaned.replace(/<task-notification>[\s\S]*?<\/task-notification>/g, '');
  cleaned = cleaned.replace(/<user-prompt-submit-hook>[\s\S]*?<\/user-prompt-submit-hook>/g, '');
  // Strip command-related blocks entirely (tag + content)
  cleaned = cleaned.replace(/<command-message>[\s\S]*?<\/command-message>/g, '');
  cleaned = cleaned.replace(/<command-name>[\s\S]*?<\/command-name>/g, '');
  cleaned = cleaned.replace(/<command-args>[\s\S]*?<\/command-args>/g, '');
  // Strip skill expansion tags (e.g. <commit>...</commit>, <simplify>...</simplify>)
  // Use backreference (\1) to match paired open/close tags, preventing nested tags
  // from causing the outer tag's trailing content to leak through.
  cleaned = cleaned.replace(/<([a-z][\w-]*)>[\s\S]*?<\/\1>/g, '');
  // Strip any remaining orphaned internal tags (opening/closing)
  cleaned = cleaned.replace(/<\/?[a-z][\w-]*(?:\s[^>]*)?>/g, '');
  cleaned = cleaned.trim();

  return cleaned || null;
}

function getSessionDir(projectPath: string): string {
  const baseDir = join(homedir(), '.claude', 'projects');
  const primary = join(baseDir, projectPath.replace(/[^a-zA-Z0-9]/g, '-'));

  if (existsSync(primary)) return primary;

  // Fallback: scan ~/.claude/projects/ for a directory whose name ends with
  // the last component(s) of the project path.  Handles cases where Claude CLI
  // resolved symlinks or used a different absolute prefix.
  try {
    const tail = projectPath.split('/').filter(Boolean).slice(-2).join('-'); // e.g. "Trinity_local_collection-step_wise_reward"
    const entries = readdirSync(baseDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory() && entry.name.endsWith(tail) && entry.name !== primary.split('/').pop()) {
        const candidate = join(baseDir, entry.name);
        console.log(`[sessions] primary dir not found (${primary}), using fallback: ${candidate}`);
        return candidate;
      }
    }
  } catch { /* ignore */ }

  console.log(`[sessions] session dir: ${primary} (exists: ${existsSync(primary)})`);
  return primary;
}

async function getFirstUserPrompt(filePath: string): Promise<{ prompt: string; gitBranch?: string } | null> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: createReadStream(filePath), crlfDelay: Infinity });
    let resolved = false;
    let gitBranch: string | undefined;
    let fallbackPrompt: string | undefined;

    rl.on('line', (line) => {
      try {
        const obj = JSON.parse(line);
        if (obj.type === 'user' && typeof obj.message?.content === 'string') {
          if (!gitBranch && obj.gitBranch) gitBranch = obj.gitBranch;

          const raw = obj.message.content as string;
          const cleaned = cleanUserMessage(raw);
          if (!cleaned) return; // system message, skip

          // Skip commands and continuation summaries for firstPrompt
          if (isCommandMessage(raw) || isContinuationMessage(raw)) {
            if (!fallbackPrompt) fallbackPrompt = cleaned;
            return;
          }

          resolved = true;
          rl.close();
          resolve({
            prompt: cleaned.slice(0, 200),
            gitBranch: gitBranch ?? obj.gitBranch,
          });
        }
      } catch { /* skip */ }
    });
    rl.on('close', () => {
      if (!resolved) {
        if (fallbackPrompt) {
          resolve({ prompt: fallbackPrompt.slice(0, 200), gitBranch });
        } else {
          resolve(null);
        }
      }
    });
    rl.on('error', () => { if (!resolved) resolve(null); });
  });
}

export async function listSessions(projectPath: string): Promise<SessionListItem[]> {
  const dir = getSessionDir(projectPath);
  if (!existsSync(dir)) return [];

  let files: string[];
  try {
    const entries = await readdir(dir);
    files = entries.filter((f) => f.endsWith('.jsonl'));
  } catch {
    return [];
  }

  const now = Date.now();
  const results: SessionListItem[] = [];
  const CONCURRENCY = 20;

  for (let i = 0; i < files.length; i += CONCURRENCY) {
    const batch = files.slice(i, i + CONCURRENCY);
    const items = await Promise.all(
      batch.map(async (file) => {
        const sessionId = file.replace('.jsonl', '');
        if (!UUID_REGEX.test(sessionId)) return null;
        const filePath = join(dir, file);
        try {
          const [fileStat, meta] = await Promise.all([stat(filePath), getFirstUserPrompt(filePath)]);
          if (!meta) return null;
          return {
            sessionId,
            firstPrompt: meta.prompt,
            lastModified: fileStat.mtime.toISOString(),
            fileSize: fileStat.size,
            gitBranch: meta.gitBranch,
            isActive: now - fileStat.mtime.getTime() <= ACTIVE_THRESHOLD_MS,
          };
        } catch { return null; }
      })
    );
    for (const item of items) {
      if (item) results.push(item);
    }
  }

  results.sort((a, b) => new Date(b.lastModified).getTime() - new Date(a.lastModified).getTime());
  return results;
}

/**
 * List only active (recently modified) CLI sessions — fast path.
 */
export async function listActiveSessions(projectPath: string): Promise<SessionListItem[]> {
  const dir = getSessionDir(projectPath);
  if (!existsSync(dir)) return [];

  let files: string[];
  try {
    const entries = await readdir(dir);
    files = entries.filter((f) => f.endsWith('.jsonl'));
  } catch {
    return [];
  }

  const now = Date.now();
  const results: SessionListItem[] = [];

  // Phase 1: stat all files to find active ones (cheap)
  const CONCURRENCY = 50;
  const activeFiles: Array<{ file: string; sessionId: string; mtime: Date; size: number }> = [];

  for (let i = 0; i < files.length; i += CONCURRENCY) {
    const batch = files.slice(i, i + CONCURRENCY);
    const items = await Promise.all(
      batch.map(async (file) => {
        const sessionId = file.replace('.jsonl', '');
        if (!UUID_REGEX.test(sessionId)) return null;
        try {
          const fileStat = await stat(join(dir, file));
          if (now - fileStat.mtime.getTime() <= ACTIVE_THRESHOLD_MS) {
            return { file, sessionId, mtime: fileStat.mtime, size: fileStat.size };
          }
        } catch { /* skip */ }
        return null;
      })
    );
    for (const item of items) {
      if (item) activeFiles.push(item);
    }
  }

  // Phase 2: read first prompt only for active files
  for (const { file, sessionId, mtime, size } of activeFiles) {
    try {
      const meta = await getFirstUserPrompt(join(dir, file));
      if (!meta) continue;
      results.push({
        sessionId,
        firstPrompt: meta.prompt,
        lastModified: mtime.toISOString(),
        fileSize: size,
        gitBranch: meta.gitBranch,
        isActive: true,
      });
    } catch { /* skip */ }
  }

  results.sort((a, b) => new Date(b.lastModified).getTime() - new Date(a.lastModified).getTime());
  return results;
}

export interface SessionSearchMatch {
  message: string;
  entryId: string;
  context: Array<{ type: string; content: string }>;
}

export interface SessionSearchResult {
  sessionId: string;
  firstPrompt: string;
  lastModified: string;
  fileSize: number;
  gitBranch?: string;
  matches: SessionSearchMatch[];
}

/**
 * Search all sessions for a query matching any user message.
 */
export async function searchSessions(projectPath: string, query: string): Promise<SessionSearchResult[]> {
  const dir = getSessionDir(projectPath);
  if (!existsSync(dir)) return [];

  let files: string[];
  try {
    const entries = await readdir(dir);
    files = entries.filter((f) => f.endsWith('.jsonl'));
  } catch {
    return [];
  }

  const q = query.toLowerCase();
  const results: SessionSearchResult[] = [];

  const CONCURRENCY = 10;
  for (let i = 0; i < files.length; i += CONCURRENCY) {
    const batch = files.slice(i, i + CONCURRENCY);
    const items = await Promise.all(
      batch.map(async (file) => {
        const sessionId = file.replace('.jsonl', '');
        if (!UUID_REGEX.test(sessionId)) return null;

        const filePath = join(dir, file);
        try {
          const [fileStat, content] = await Promise.all([stat(filePath), readFile(filePath, 'utf-8')]);

          // Parse into entries
          const lines = content.split('\n').filter(l => l.trim());
          const entries: SessionTimelineEntry[] = [];
          let counter = 0;

          for (const line of lines) {
            let obj: Record<string, unknown>;
            try { obj = JSON.parse(line); } catch { continue; }
            const type = obj.type as string;
            if (type === 'queue-operation' || type === 'system') continue;
            const timestamp = obj.timestamp ? new Date(obj.timestamp as string).getTime() : 0;
            const message = obj.message as { content?: unknown } | undefined;
            if (!message) continue;

            if (type === 'user' && typeof message.content === 'string') {
              const cleaned = cleanUserMessage(message.content);
              if (cleaned) {
                entries.push({ id: `user-${counter++}`, type: 'user_message', timestamp, content: cleaned });
              }
            } else if (type === 'assistant' && Array.isArray(message.content)) {
              for (const block of message.content as Array<Record<string, unknown>>) {
                if (block.type === 'text' && (block.text as string).trim()) {
                  entries.push({ id: `text-${counter++}`, type: 'output', timestamp, content: block.text as string });
                }
              }
            }
          }

          // Search user_message entries
          let firstPrompt = '';
          let gitBranch: string | undefined;
          const allMatches: SessionSearchMatch[] = [];

          // Try to get gitBranch from first JSONL line
          const firstLine = content.split('\n').find(l => l.trim());
          if (firstLine) {
            try {
              const obj = JSON.parse(firstLine);
              if (obj.gitBranch) gitBranch = obj.gitBranch;
            } catch { /* skip */ }
          }

          for (let ei = 0; ei < entries.length; ei++) {
            const entry = entries[ei];
            if (entry.type === 'user_message') {
              if (!firstPrompt && !isCommandMessage(entry.content) && !isContinuationMessage(entry.content)) {
                firstPrompt = entry.content;
              } else if (!firstPrompt) {
                firstPrompt = entry.content;
              }

              if (entry.content.toLowerCase().includes(q)) {
                const context: Array<{ type: string; content: string }> = [];
                // Look backward
                for (let bi = ei - 1; bi >= Math.max(0, ei - 3); bi--) {
                  const prev = entries[bi];
                  if (prev.type === 'tool_result' || prev.type === 'tool_use') continue;
                  context.unshift({ type: prev.type, content: prev.content.slice(0, 200) });
                  break;
                }
                // Look forward
                for (let fi = ei + 1; fi < Math.min(entries.length, ei + 4); fi++) {
                  const next = entries[fi];
                  if (next.type === 'tool_result' || next.type === 'tool_use') continue;
                  context.push({ type: next.type, content: next.content.slice(0, 200) });
                  break;
                }
                allMatches.push({ message: entry.content.slice(0, 300), entryId: entry.id, context });
              }
            }
          }

          if (allMatches.length === 0) return null;

          return {
            sessionId,
            firstPrompt: firstPrompt.slice(0, 200),
            lastModified: fileStat.mtime.toISOString(),
            fileSize: fileStat.size,
            gitBranch,
            matches: allMatches,
          } satisfies SessionSearchResult;
        } catch {
          return null;
        }
      })
    );
    for (const item of items) {
      if (item) results.push(item);
    }
  }

  results.sort((a, b) => new Date(b.lastModified).getTime() - new Date(a.lastModified).getTime());
  return results;
}

export async function getSessionDetail(projectPath: string, sessionId: string): Promise<SessionTimelineEntry[] | null> {
  if (!UUID_REGEX.test(sessionId)) return null;

  const filePath = join(getSessionDir(projectPath), `${sessionId}.jsonl`);
  if (!existsSync(filePath)) return null;

  let content: string;
  try {
    content = await readFile(filePath, 'utf-8');
  } catch {
    return null;
  }

  const lines = content.split('\n').filter((l) => l.trim());
  const entries: SessionTimelineEntry[] = [];
  let counter = 0;
  const toolUseMap = new Map<string, SessionTimelineEntry>();

  for (const line of lines) {
    let obj: Record<string, unknown>;
    try { obj = JSON.parse(line); } catch { continue; }

    const type = obj.type as string;
    if (type === 'queue-operation' || type === 'system') continue;

    const timestamp = obj.timestamp ? new Date(obj.timestamp as string).getTime() : 0;
    const message = obj.message as { content?: unknown } | undefined;
    if (!message) continue;

    if (type === 'user') {
      if (typeof message.content === 'string') {
        const cleaned = cleanUserMessage(message.content as string);
        if (cleaned) {
          entries.push({ id: `user-${counter++}`, type: 'user_message', timestamp, content: cleaned });
        }
      } else if (Array.isArray(message.content)) {
        for (const block of message.content as Array<Record<string, unknown>>) {
          if (block.type === 'tool_result') {
            const toolUseId = block.tool_use_id as string;
            const bc = block.content;
            const resultText = typeof bc === 'string' ? bc
              : Array.isArray(bc) ? (bc as Array<Record<string, unknown>>).filter(b => b.type === 'text').map(b => b.text as string).join('\n')
              : JSON.stringify(bc);
            const match = toolUseMap.get(toolUseId);
            if (match) { match.toolResult = resultText; }
            else { entries.push({ id: `result-${counter++}`, type: 'tool_result', timestamp, content: '', toolResult: resultText }); }
          }
        }
      }
    } else if (type === 'assistant' && Array.isArray(message.content)) {
      for (const block of message.content as Array<Record<string, unknown>>) {
        if (block.type === 'text' && (block.text as string).trim()) {
          entries.push({ id: `text-${counter++}`, type: 'output', timestamp, content: block.text as string });
        } else if (block.type === 'tool_use') {
          const entry: SessionTimelineEntry = {
            id: `tool-${block.id || counter++}`, type: 'tool_use', timestamp, content: '',
            toolName: block.name as string, toolInput: block.input,
          };
          entries.push(entry);
          if (block.id) toolUseMap.set(block.id as string, entry);
        }
      }
    }
  }

  return entries;
}
